In [1]:
import pandas as pd
import numpy as np
import kagglehub
import os
import requests
from bs4 import BeautifulSoup
import re, json

In [19]:
path = kagglehub.dataset_download("turarr/astana-real-estate-dataset")

print("Path to dataset files:", path)

Downloading to /home/codespace/.cache/kagglehub/datasets/turarr/astana-real-estate-dataset/1.archive...

100%|███████████████████████████████████████████████████████████████████████████████| 307k/307k [00:01<00:00, 286kB/s]

Extracting files...
Path to dataset files: /home/codespace/.cache/kagglehub/datasets/turarr/astana-real-estate-dataset/versions/1

In [20]:
print(os.listdir(path))

['astana_real_estate_dataset.csv']

In [22]:
df = pd.read_csv(os.path.join(path, "astana_real_estate_dataset.csv"))
df.head()

,url,title,price,security,ceiling_height,Год постройки,district,residential_complex,furnished,parking,...,rooms,current_floor,total_floors,area_m2,address,district_lat,district_lon,apartment_lat,apartment_lon,coord_level
0,https://krisha.kz/a/show/683656844,"3-комнатная квартира · 120 м², Сыганак — Кабан...",55000000,"домофон, видеонаблюдение",2.902672,2006,"Есильский район, Астана, Казахстан",7 Бочек,полностью,Во дворе/не указано,...,3.0,6.0,11.0,120.00,Сыганак — Кабанбай батыра,51.120,71.430,51.122041,71.413101,Address
1,https://krisha.kz/a/show/1010380882,"2-комнатная квартира · 64.5 м² · 9/9 этаж, Тол...",45500000,"домофон, видеонаблюдение",3.000000,2022,"Нуринский район, Астана, Казахстан",Dastur,полностью,Во дворе/не указано,...,2.0,9.0,9.0,64.50,Толе би 25,51.100,71.380,51.099779,71.389694,Complex
2,https://krisha.kz/a/show/1010251370,"2-комнатная квартира · 64.37 м² · 10/12 этаж, ...",32800000,"домофон, кодовый замок, видеодомофон",3.000000,2026,"Сарыаркинский район, Астана, Казахстан",Shalqar,без мебели,паркинг,...,2.0,10.0,12.0,64.37,Чингиз Айтматов 77/11 — Мечеть Ырыскелді Кажы,51.170,71.410,51.170000,71.410000,District
3,https://krisha.kz/a/show/1010195327,"3-комнатная квартира · 115 м², Ивана Панфилова 85",75000000,"домофон, видеонаблюдение",3.200000,2026,"Сарыаркинский район, Астана, Казахстан",TANSU,без мебели,паркинг,...,3.0,6.0,11.0,115.00,Ивана Панфилова 85,51.117,71.565,51.105860,71.500377,Complex
4,https://krisha.kz/a/show/1009176178,"2-комнатная квартира · 52 м² · 8/12 этаж, Кубр...",25000000,"домофон, видеонаблюдение",2.700000,2009,"Сарыаркинский район, Астана, Казахстан",Сайран,полностью,Во дворе/не указано,...,2.0,8.0,12.0,52.00,Кубрина 20/1,51.170,71.410,51.197097,71.475239,Complex

In [4]:
html = requests.get(
    "https://krisha.kz/a/show/1010380882",
    headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
).text

In [5]:
soup = BeautifulSoup(html, 'html.parser')
script_tag = soup.find('script', {'id': 'jsdata'})

In [6]:
print(script_tag is None)        # is the tag even found?
print(script_tag.string[:500])   # what does it actually contain?

False

        window.data = {"advert":{"id":1010380882,"storage":"live","commentsType":"adv","isCommentable":false,"isCommentableByEveryone":false,"isOnMap":true,"hasPrice":true,"price":45500000,"photos":[{"src":"https://krisha-photos.kcdn.online/webp/16/16b04afe-aa24-414f-be8f-c43dd86cf63f/17-full.jpg","w":675,"h":900,"title":"Продажа квартир в Астане: 2-комнатная квартира · 64.5 м² · 9/9 этаж, Толе би 25 за 45.5 млн ₸ — фото 18","alt":"2-комнатная квартира · 64.5 м² · 9/9 этаж, Толе би 25 за 45.5 м

In [8]:
match = re.search(r'window\.data\s*=\s*(\{.+\});', script_tag.string, re.DOTALL)
data = json.loads(match.group(1))
print(data['advert'].get('lat'), data['advert'].get('lon'))

None None

In [9]:
print(data['advert'].keys())

dict_keys(['id', 'storage', 'commentsType', 'isCommentable', 'isCommentableByEveryone', 'isOnMap', 'hasPrice', 'price', 'photos', 'hasPackages', 'title', 'addressTitle', 'userType', 'square', 'rooms', 'ownerName', 'status', 'complexId', 'map', 'sectionAlias', 'categoryId', 'categoryAlias', 'address', 'isEstateVerified', 'isOwnedByCurrentUser', 'hasRelatedCompilation', 'isBookingEnabled'])

In [10]:
matches = re.findall(r'51\.\d+', script_tag.string)
print(matches)

['51.0983394237', '51.015405', '51.259035', '51.306666', '51.331666', '51.378815', '51.217734', '51.02963', '51.991758', '51.989277', '51.248864', '51.568736', '51.225437', '51.580605', '51.155685', '51.56813', '51.03227', '51.241077', '51.048987', '51.217932', '51.217896', '51.272711', '51.243037', '51.258108', '51.293382', '51.265796', '51.295239', '51.323377', '51.31411', '51.353126', '51.281324', '51.446775', '51.289132', '51.535491', '51.248864', '51.568736', '51.81079', '51.773854', '51.783515', '51.838706', '51.861149', '51.876595', '51.983982', '51.972771', '51.928291', '51.917185', '51.882894', '51.873782', '51.837904', '51.823097', '51.852235', '51.819873', '51.780297', '51.81079', '51.078633', '51.269189', '51.342392', '51.730008', '51.836542', '51.737094', '51.635567', '51.557783', '51.262286', '51.132642', '51.077578', '51.071017', '51.096811']

In [11]:
print(data['advert']['map'])

{'lat': 51.0983394237, 'lon': 71.386782584758, 'zoom': 17, 'type': None}

In [4]:
df1 = pd.read_csv("krisha_data_raw_orig.csv")
df1.head()

,url,title,price,lat,lon,Балкон,Балкон остеклён,Безопасность,Бывшее общежитие,Возможен обмен,...,Интернет,Квартира меблирована,Парковка,Площадь,Пол,Санузел,Состояние квартиры,Телефон,Тип дома,Этаж
0,https://krisha.kz/a/show/1011890902,"2-комнатная квартира · 63 м² · 11/12 этаж, Бок...",48500000,51.090252,71.427670,лоджия,NaN,"охрана, домофон, кодовый замок, видеонаблюдение",нет,Нет,...,оптика,полностью,паркинг,"63 м², Площадь кухни — 12 м²",ламинат,совмещенный,свежий ремонт,NaN,монолитный,11 из 12
1,https://krisha.kz/a/show/1011872179,"2-комнатная квартира · 59 м² · 2/9 этаж, Ахмет...",38500000,51.116968,71.505137,лоджия,NaN,"охрана, кодовый замок, видеонаблюдение, видеод...",нет,Нет,...,оптика,полностью,рядом охраняемая стоянка,"59 м², Площадь кухни — 10.1 м²",ламинат,совмещенный,свежий ремонт,NaN,монолитный,2 из 9
2,https://krisha.kz/a/show/1010675410,"2-комнатная квартира · 50 м² · 14/19 этаж, Жош...",44000000,51.101315,71.439466,лоджия,NaN,"охрана, кодовый замок, видеонаблюдение, видеод...",нет,Нет,...,оптика,полностью,паркинг,50 м²,ламинат,совмещенный,свежий ремонт,NaN,монолитный,14 из 19
3,https://krisha.kz/a/show/1012729246,"4-комнатная квартира · 225 м² · 5/18 этаж, Дин...",300000000,51.129934,71.424512,NaN,NaN,NaN,нет,Нет,...,NaN,NaN,паркинг,225 м²,NaN,NaN,NaN,NaN,монолитный,5 из 18
4,https://krisha.kz/a/show/1009888824,"3-комнатная квартира · 88 м² · 8/10 этаж, Сыга...",42900000,51.121237,71.431714,лоджия,NaN,видеонаблюдение,нет,Да,...,NaN,NaN,паркинг,"88 м², Площадь кухни — 13 м²",ламинат,NaN,NaN,NaN,монолитный,8 из 10

In [5]:
df2 = pd.read_csv("krisha_data_raw.csv")
df2.head()

,url,title,price,lat,lon,Балкон,Балкон остеклён,Безопасность,Бывшее общежитие,Возможен обмен,...,Интернет,Квартира меблирована,Парковка,Площадь,Пол,Санузел,Состояние квартиры,Телефон,Тип дома,Этаж
0,https://krisha.kz/a/show/1009399736,"2-комнатная квартира · 71 м² · 9/9 этаж, Шамши...",49500000,51.115265,71.474642,лоджия,NaN,NaN,нет,Нет,...,NaN,NaN,паркинг,71 м²,NaN,совмещенный,черновая отделка,NaN,кирпичный,9 из 9
1,https://krisha.kz/a/show/1007781992,"2-комнатная квартира · 46 м² · 5/5 этаж, боген...",19000000,51.176184,71.409813,балкон,NaN,"домофон, видеонаблюдение",NaN,Нет,...,проводной,полностью,рядом охраняемая стоянка,46 м²,ламинат,совмещенный,NaN,есть возможность подключения,кирпичный,5 из 5
2,https://krisha.kz/a/show/1012946950,"4-комнатная квартира · 89 м² · 3/5 этаж, Жабае...",24550000,51.146339,71.558194,балкон,да,NaN,нет,Нет,...,NaN,полностью,NaN,89 м²,NaN,раздельный,NaN,NaN,монолитный,3 из 5
3,https://krisha.kz/a/show/1012626568,"1-комнатная квартира · 41 м² · 4/9 этаж, А91 17",25500000,51.119013,71.530142,балкон,NaN,NaN,нет,Нет,...,проводной,полностью,паркинг,41 м²,NaN,совмещенный,"не новый, но аккуратный ремонт",есть возможность подключения,монолитный,4 из 9
4,https://krisha.kz/a/show/697912304,"4-комнатная квартира · 139 м² · 13/22 этаж, Е-...",175000000,51.134748,71.401212,лоджия,NaN,"охрана, домофон, кодовый замок, сигнализация, ...",нет,Нет,...,NaN,NaN,паркинг,139 м²,NaN,2 с/у и более,черновая отделка,NaN,монолитный,13 из 22

In [12]:
df_full = pd.concat([df1, df2], ignore_index=True)
len(df_full)

20022

In [13]:
num_duplicates = df_full.duplicated().sum()
print(num_duplicates)

2452

In [14]:
df_full = df_full.drop_duplicates(subset='url')
len(df_full)

16075

In [8]:
is_all_unique = not df_full.duplicated().any()
is_all_unique

True

In [15]:
df_full.head()

,url,title,price,lat,lon,Балкон,Балкон остеклён,Безопасность,Бывшее общежитие,Возможен обмен,...,Интернет,Квартира меблирована,Парковка,Площадь,Пол,Санузел,Состояние квартиры,Телефон,Тип дома,Этаж
0,https://krisha.kz/a/show/1011890902,"2-комнатная квартира · 63 м² · 11/12 этаж, Бок...",48500000,51.090252,71.427670,лоджия,NaN,"охрана, домофон, кодовый замок, видеонаблюдение",нет,Нет,...,оптика,полностью,паркинг,"63 м², Площадь кухни — 12 м²",ламинат,совмещенный,свежий ремонт,NaN,монолитный,11 из 12
1,https://krisha.kz/a/show/1011872179,"2-комнатная квартира · 59 м² · 2/9 этаж, Ахмет...",38500000,51.116968,71.505137,лоджия,NaN,"охрана, кодовый замок, видеонаблюдение, видеод...",нет,Нет,...,оптика,полностью,рядом охраняемая стоянка,"59 м², Площадь кухни — 10.1 м²",ламинат,совмещенный,свежий ремонт,NaN,монолитный,2 из 9
2,https://krisha.kz/a/show/1010675410,"2-комнатная квартира · 50 м² · 14/19 этаж, Жош...",44000000,51.101315,71.439466,лоджия,NaN,"охрана, кодовый замок, видеонаблюдение, видеод...",нет,Нет,...,оптика,полностью,паркинг,50 м²,ламинат,совмещенный,свежий ремонт,NaN,монолитный,14 из 19
3,https://krisha.kz/a/show/1012729246,"4-комнатная квартира · 225 м² · 5/18 этаж, Дин...",300000000,51.129934,71.424512,NaN,NaN,NaN,нет,Нет,...,NaN,NaN,паркинг,225 м²,NaN,NaN,NaN,NaN,монолитный,5 из 18
4,https://krisha.kz/a/show/1009888824,"3-комнатная квартира · 88 м² · 8/10 этаж, Сыга...",42900000,51.121237,71.431714,лоджия,NaN,видеонаблюдение,нет,Да,...,NaN,NaN,паркинг,"88 м², Площадь кухни — 13 м²",ламинат,NaN,NaN,NaN,монолитный,8 из 10